// ---------- ДОСТИЖЕНИЯ: основные, секретные, комбо, баланс ----------

export const ACHIEVEMENTS = [
  {
    id: 'run_distance',
    title: 'Дистанция забега',
    activity: 'running',
    kind: 'single_value', // best single value of `distance`
    tiers: [
      { tier: 'bronze', name: 'Бронза', need: 3 },
      { tier: 'silver', name: 'Серебро', need: 5 },
      { tier: 'gold', name: 'Золото', need: 10 },
    ],
    unit: 'км',
  },
  {
    id: 'run_streak',
    title: 'Бег по дням подряд',
    activity: 'running',
    kind: 'streak',
    tiers: [
      { tier: 'bronze', name: 'Бронза', need: 3 },
      { tier: 'silver', name: 'Серебро', need: 5 },
      { tier: 'gold', name: 'Золото', need: 10 },
    ],
    unit: 'дней',
  },
  {
    id: 'run_total_km',
    title: 'Суммарный километраж',
    activity: 'running',
    kind: 'cumulative_value',
    tiers: [
      { tier: 'bronze', name: 'Черепашка, но не ниндзя', need: 20 },
      { tier: 'silver', name: 'Марафонец, который погиб', need: 40 },
      { tier: 'gold', name: 'Одна извилина триатлона', need: 80 },
      { tier: 'platinum', name: 'Выносливость его боялась', need: 100 },
    ],
    unit: 'км всего',
  },
  {
    id: 'strength_park_style',
    title: 'Силовой стиль',
    activity: 'strength_park',
    kind: 'count',
    tiers: [{ tier: 'special', name: 'Лесной олимпийский эльф', need: 1 }],
    unit: 'раз',
    flavor: 'Силовая на турниках или в парке',
  },
  {
    id: 'strength_park_total',
    title: 'Всего тренировок на турниках/парке',
    activity: 'strength_park',
    kind: 'cumulative_count',
    tiers: [
      { tier: 'bronze', name: 'Зелёная веточка', need: 12 },
      { tier: 'silver', name: 'Смотрящий за турником', need: 24 },
      { tier: 'gold', name: 'Спортик', need: 48 },
      { tier: 'platinum', name: 'Кто припарковал машину?', need: 77 },
      { tier: 'diamond', name: 'Отлетевший кроссфитер', need: 100 },
    ],
    unit: 'тренировок',
  },
  {
    id: 'strength_gym_style',
    title: 'Силовой стиль',
    activity: 'strength_gym',
    kind: 'count',
    tiers: [{ tier: 'special', name: 'Варварский налёт на блины', need: 1 }],
    unit: 'раз',
    flavor: 'Силовая в спортзале',
  },
  {
    id: 'strength_gym_total',
    title: 'Всего тренировок в зале',
    activity: 'strength_gym',
    kind: 'cumulative_count',
    tiers: [
      { tier: 'bronze', name: 'Уаз патриот', need: 12 },
      { tier: 'silver', name: 'Гнущий линии', need: 40 },
      { tier: 'gold', name: 'Медоед', need: 80 },
      { tier: 'platinum', name: 'Стальной химик', need: 100 },
    ],
    unit: 'тренировок',
  },
  {
    id: 'wrestling_style',
    title: 'Силовой стиль',
    activity: 'wrestling',
    kind: 'count',
    tiers: [{ tier: 'special', name: 'Дварфийский прогиб', need: 1 }],
    unit: 'раз',
    flavor: 'Борьба / единоборства',
  },
  {
    id: 'wrestling_total',
    title: 'Всего тренировок по борьбе',
    activity: 'wrestling',
    kind: 'cumulative_count',
    tiers: [
      { tier: 'bronze', name: 'Гардпулер', need: 12 },
      { tier: 'silver', name: 'Силовичок', need: 24 },
      { tier: 'gold', name: 'Завязывающий узлы', need: 48 },
      { tier: 'platinum', name: 'Его называли домкрат', need: 77 },
      { tier: 'diamond', name: 'Гордость Дагестана', need: 100 },
    ],
    unit: 'тренировок',
  },
  {
    id: 'strength_weekly',
    title: 'Силовые по дням (в неделю)',
    activity: ['strength_park', 'strength_gym', 'wrestling'],
    kind: 'weekly_count',
    tiers: [
      { tier: 'bronze', name: 'Бегущий по лени', need: 1 },
      { tier: 'silver', name: 'Нормис', need: 2 },
      { tier: 'gold', name: 'Еее бадди', need: 3 },
      { tier: 'platinum', name: 'Батя в лучшие годы', need: 4 },
    ],
    unit: 'раз/нед',
  },
  {
    id: 'nutrition_streak',
    title: 'Питание по дням подряд',
    activity: 'nutrition',
    kind: 'streak',
    tiers: [
      { tier: 'bronze', name: 'Свинка Пеппа', need: 3 },
      { tier: 'silver', name: 'Сильвольный борец', need: 5 },
      { tier: 'gold', name: 'Дисциплинатор 3000', need: 7 },
    ],
    unit: 'дней',
  },
  {
    id: 'nutrition_total',
    title: 'Всего дней здорового питания',
    activity: 'nutrition',
    kind: 'cumulative_count',
    tiers: [
      { tier: 'bronze', name: 'Ищем пресс', need: 14 },
      { tier: 'silver', name: 'Волевой зараза', need: 28 },
      { tier: 'gold', name: 'Карающий калории', need: 56 },
      { tier: 'platinum', name: 'Истязающий жиры', need: 77 },
      { tier: 'diamond', name: 'Я есть пресс', need: 100 },
    ],
    unit: 'дней',
  },
  {
    id: 'sleep_streak',
    title: 'Здоровый сон по дням подряд',
    activity: 'sleep',
    kind: 'streak',
    tiers: [
      { tier: 'bronze', name: 'Сонный паралич', need: 3 },
      { tier: 'silver', name: 'Мелатонин', need: 5 },
      { tier: 'gold', name: 'Морфей', need: 10 },
    ],
    unit: 'дней',
  },
  {
    id: 'sleep_total',
    title: 'Всего дней здорового сна',
    activity: 'sleep',
    kind: 'cumulative_count',
    tiers: [
      { tier: 'bronze', name: 'Улитка', need: 3 },
      { tier: 'silver', name: 'Восстановитель ЦНС', need: 7 },
      { tier: 'gold', name: 'Магистр циркадных ритмов', need: 14 },
      { tier: 'platinum', name: 'Морфеус мать его', need: 28 },
    ],
    unit: 'дней',
  },
  {
    id: 'reading_streak',
    title: 'Чтение по дням подряд',
    activity: 'reading',
    kind: 'streak',
    tiers: [
      { tier: 'bronze', name: 'Книжный червь', need: 3 },
      { tier: 'silver', name: 'Умник', need: 5 },
      { tier: 'gold', name: 'Евгений Викторович Жаринов', need: 10 },
    ],
    unit: 'дней',
  },
  {
    id: 'reading_total',
    title: 'Всего дней чтения',
    activity: 'reading',
    kind: 'cumulative_count',
    tiers: [
      { tier: 'bronze', name: 'Библиотечная пыль', need: 3 },
      { tier: 'silver', name: 'Книжный воротила', need: 5 },
      { tier: 'gold', name: 'Ну этот, как его там, в общем он', need: 10 },
      { tier: 'platinum', name: 'Воспевший интеллект', need: 20 },
      { tier: 'special', name: 'Мозговитый хитроумный', need: 40 },
      { tier: 'diamond', name: 'Режущий бумагу остротой ума', need: 60 },
      { tier: 'legend', name: 'Крутой библиотекарь книгодзука', need: 100 },
    ],
    unit: 'дней',
  },
  {
    id: 'reading_pages',
    title: 'Суммарно страниц прочитано',
    activity: 'reading',
    kind: 'cumulative_pages',
    tiers: [
      { tier: 'bronze',   name: 'Первые строчки',           need: 50 },
      { tier: 'silver',   name: 'Дочитал до половины',      need: 100 },
      { tier: 'gold',     name: 'Прочитанная книга',        need: 300 },
      { tier: 'platinum', name: 'Книжная полка',            need: 500 },
      { tier: 'special',  name: 'Библиотекарь',             need: 1000 },
      { tier: 'diamond',  name: 'Пожиратель книг',          need: 2000 },
      { tier: 'legend',   name: 'Легенда читального зала',  need: 5000 },
    ],
    unit: 'стр',
  },
  {
    id: 'reading_books',
    title: 'Завершено книг',
    activity: 'reading',
    kind: 'books_finished',
    tiers: [
      { tier: 'bronze',   name: 'Первая прочитанная',       need: 1,  rewards: { 'Интеллект': 5,  'Мышление': 3 } },
      { tier: 'gold',     name: 'Три тома мудрости',        need: 3,  rewards: { 'Интеллект': 8,  'Мышление': 5 } },
      { tier: 'platinum', name: 'Пять источников знаний',   need: 5,  rewards: { 'Интеллект': 12, 'Мышление': 8 } },
      { tier: 'diamond',  name: 'Десять миров',             need: 10, rewards: { 'Интеллект': 10, 'Мышление': 6 } },
    ],
    unit: 'книг',
  },
  {
    id: 'cal_best_day',
    title: 'Рекорд сжигания за день',
    activity: 'calories',
    kind: 'cal_single_day',
    tiers: [
      { tier: 'bronze', name: 'Зажигалочка', need: 300 },
      { tier: 'silver', name: 'Солнечный удар', need: 500 },
      { tier: 'gold', name: 'Тлеющий в легионе', need: 800 },
      { tier: 'platinum', name: 'Сказочная печка', need: 1000 },
      { tier: 'special', name: 'Жечь, жечь!', need: 1300 },
      { tier: 'diamond', name: 'Топка судьбы', need: 1600 },
    ],
    unit: 'ккал/день',
  },
  {
    id: 'cal_streak_300',
    title: 'Стрик 300+ ккал/день',
    activity: 'calories',
    kind: 'cal_streak_threshold',
    threshold: 300,
    tiers: [
      { tier: 'bronze', name: 'Деревянная пепельница', need: 5 },
      { tier: 'silver', name: 'Медная пепельница', need: 10 },
      { tier: 'gold', name: 'Бронзовая пепельница', need: 30 },
    ],
    unit: 'дней подряд',
  },
  {
    id: 'cal_streak_500',
    title: 'Стрик 500+ ккал/день',
    activity: 'calories',
    kind: 'cal_streak_threshold',
    threshold: 500,
    tiers: [
      { tier: 'bronze', name: 'Фитилёк', need: 5 },
      { tier: 'silver', name: 'Пылающий бензобак', need: 10 },
      { tier: 'gold', name: 'Взрывная красная бочка', need: 30 },
    ],
    unit: 'дней подряд',
  },
  {
    id: 'cal_total',
    title: 'Суммарно сожжено ккал',
    activity: 'calories',
    kind: 'cal_cumulative',
    tiers: [
      { tier: 'bronze', name: 'Искорка', need: 1000 },
      { tier: 'silver', name: 'Костерок', need: 3000 },
      { tier: 'gold', name: 'Проблема пожарного', need: 8000 },
      { tier: 'platinum', name: 'Лесное пожарище', need: 15000 },
      { tier: 'special', name: 'Сжигатель миров', need: 20000 },
      { tier: 'diamond', name: 'Магма течёт! (но пока не в венах)', need: 30000 },
    ],
    unit: 'ккал всего',
  },
  // ── ХОДЬБА ──────────────────────────────────────────
  {
    id: 'steps_first_day',
    title: 'Первоход',
    activity: 'walking',
    kind: 'steps_single_day',
    tiers: [{ tier: 'bronze', name: 'Первоход', need: 5000 }],
    unit: 'шагов за день',
  },
  {
    id: 'steps_total_100k',
    title: 'Суммарно шагов',
    activity: 'walking',
    kind: 'steps_cumulative',
    tiers: [
      { tier: 'bronze',   name: 'Бродяга симпатяга',                    need: 100000 },
      { tier: 'silver',   name: 'Всё ещё в Шире',                       need: 500000 },
      { tier: 'gold',     name: 'Бродят волки по дорогам скрипачей',     need: 1000000 },
    ],
    unit: 'шагов всего',
  },
  {
    id: 'steps_20k_day',
    title: 'Шаолиньское кунг-фу',
    activity: 'walking',
    kind: 'steps_single_day',
    tiers: [{ tier: 'gold', name: 'Шаолиньское кунг-фу', need: 20000 }],
    unit: 'шагов за день',
  },
  {
    id: 'steps_streak_5k_7d',
    title: 'Неделя на ногах',
    activity: 'walking',
    kind: 'steps_streak_threshold',
    threshold: 5000,
    tiers: [{ tier: 'silver', name: 'Неделя на ногах', need: 7 }],
    unit: 'дней подряд 5к+',
    flavor: 'Твои ноги подали заявление об увольнении. Отклонено',
  },
  {
    id: 'steps_streak_7k_14d',
    title: 'Железная нога',
    activity: 'walking',
    kind: 'steps_streak_threshold',
    threshold: 7000,
    tiers: [{ tier: 'gold', name: 'Железная нога', need: 14 }],
    unit: 'дней подряд 7к+',
    flavor: 'Обувные магазины ненавидят этого человека',
  },
  {
    id: 'steps_streak_10k_30d',
    title: '100 000 лиг',
    activity: 'walking',
    kind: 'steps_streak_threshold',
    threshold: 10000,
    tiers: [{ tier: 'platinum', name: '100 000 лиг', need: 30 }],
    unit: 'дней подряд 10к+',
  },
  // ── СТЕНА ПОДВИГОВ ──────────────────────────────────────────
  {
    id: 'records_first',
    title: 'Первый рубеж',
    activity: null,
    kind: 'records_broken_count',
    tiers: [{ tier: 'bronze', name: 'Первый рубеж', need: 1 }],
    unit: 'рекордов побито',
  },
  {
    id: 'records_hunter',
    title: 'Охотник за рекордами',
    activity: null,
    kind: 'records_broken_count',
    tiers: [{ tier: 'silver', name: 'Охотник за рекордами', need: 10 }],
    unit: 'рекордов побито',
  },
  {
    id: 'records_self_rival',
    title: 'Сам себе соперник',
    activity: null,
    kind: 'records_broken_count',
    tiers: [{ tier: 'gold', name: 'Сам себе соперник', need: 25 }],
    unit: 'рекордов побито',
  },
];

// Secret achievements: single-tier, hidden until unlocked, each with a custom check function
// receiving the full computed context (logs, passiveLogs, books, streaks, etc).
export const SECRET_ACHIEVEMENTS = [
  {
    id: 'secret_colonel_sanders',
    title: 'Полковник Сандерс',
    hint: 'Связано с режимом питания',
    check: (ctx) => ctx.violatingCheatMealDays.size > 0,
  },
  {
    id: 'secret_steel_alchemist',
    title: 'Стальной алхимик',
    hint: 'Идеальный день, сошедшийся во всём',
    check: (ctx) => ctx.hasPerfectDay,
  },
  {
    id: 'secret_dry_as_desert',
    title: 'Сухой как пустыня',
    hint: 'Долгая дисциплина в питании',
    check: (ctx) => (ctx.streaksByActivity.nutrition || 0) >= 30,
  },
  {
    id: 'secret_matrix_reloaded',
    title: 'Матрица: перезагрузка',
    hint: 'Иногда нужно остановиться',
    check: (ctx) => ctx.maxZeroActivityStreak >= 3,
  },
  {
    id: 'secret_living_marathoner',
    title: 'Живой марафонец',
    hint: 'Беговая выносливость за неделю',
    check: (ctx) => ctx.maxWeeklyRunDistance >= 42,
  },
  {
    id: 'secret_biblio_globus',
    title: 'Библио-Глобус',
    hint: 'Книжный марафон за месяц',
    check: (ctx) => ctx.maxMonthlyBooksFinished >= 4,
    unlocksTab: 'archive',
  },
  {
    id: 'secret_war_machine',
    title: 'Боевая машина',
    hint: 'Месяц, прожитый на ковре',
    check: (ctx) => ctx.maxMonthlyWrestlingCount >= 18,
  },
  // --- Recovery secret achievements: hidden until unlocked, each ties to one recovery type.
  // Short recovery types unlock at 20 uses; long at 10; rest at 30. Each grants a small stat reward.
  {
    id: 'secret_recovery_walk',
    title: 'Панасенков',
    hint: 'Ходьба вдумчивая',
    check: (ctx) => (ctx.recoveryCountsByType.walk || 0) >= 20,
    rewards: { 'Дух': 5, 'Выносливость': 3 },
  },
  {
    id: 'secret_recovery_breathing',
    title: 'Кислородный сомелье',
    hint: 'Дегустация вдохов',
    check: (ctx) => (ctx.recoveryCountsByType.breathing || 0) >= 20,
    rewards: { 'Фокус': 5, 'Дух': 3 },
  },
  {
    id: 'secret_recovery_stretching',
    title: 'Гому Гому но растяжка',
    hint: 'Резиновая гибкость',
    check: (ctx) => (ctx.recoveryCountsByType.stretching || 0) >= 20,
    rewards: { 'Гибкость': 5, 'Силовая выносливость': 3 },
  },
  {
    id: 'secret_recovery_dancing',
    title: 'Диско Элизиум',
    hint: 'Ритм принимает над тобой контроль',
    check: (ctx) => (ctx.recoveryCountsByType.dancing || 0) >= 20,
    rewards: { 'Гибкость': 5, 'Воля': 3 },
  },
  {
    id: 'secret_recovery_hobby',
    title: 'Бесполезные страсти',
    hint: 'Мастерство ни к чему не ведёт, и в этом смысл',
    check: (ctx) => (ctx.recoveryCountsByType.hobby || 0) >= 20,
    rewards: { 'Фокус': 5, 'Интеллект': 3 },
  },
  {
    id: 'secret_recovery_sauna',
    title: 'Электровеник',
    hint: 'Пар пробирает до костей',
    check: (ctx) => (ctx.recoveryCountsByType.sauna || 0) >= 10,
    rewards: { 'ХП': 5, 'Дисциплина': 3 },
  },
  {
    id: 'secret_recovery_therapy',
    title: 'Обработать за 60 минут',
    hint: 'Кушетка, часы, тишина',
    check: (ctx) => (ctx.recoveryCountsByType.therapy || 0) >= 10,
    rewards: { 'Мышление': 5, 'ХП': 3 },
  },
  {
    id: 'secret_recovery_travel',
    title: 'Билет в один конец',
    hint: 'Куда угодно, лишь бы подальше',
    check: (ctx) => (ctx.recoveryCountsByType.travel || 0) >= 10,
    rewards: { 'Воля': 5, 'Интеллект': 5 },
  },
  {
    id: 'secret_recovery_nature',
    title: 'Панасенков и кусты',
    hint: 'Разговор с деревьями',
    check: (ctx) => (ctx.recoveryCountsByType.nature || 0) >= 10,
    rewards: { 'Дух': 5, 'Выносливость': 5 },
  },
  {
    id: 'secret_recovery_socializing',
    title: 'Душа компании имени себя',
    hint: 'Лица меняются, ты остаёшься',
    check: (ctx) => (ctx.recoveryCountsByType.socializing || 0) >= 10,
    rewards: { 'Дух': 5, 'Мышление': 3 },
  },
  {
    id: 'secret_recovery_rest',
    title: 'Заземление на диване',
    hint: 'Лежать — тоже искусство',
    check: (ctx) => (ctx.recoveryCountsByType.rest || 0) >= 30,
    rewards: { 'ХП': 5, 'Дисциплина': 3 },
  },
  {
    id: 'secret_recovery_good_sleep',
    title: 'Спящая красавица',
    hint: 'Выспаться 10 раз — теперь это суперспособность',
    check: (ctx) => (ctx.recoveryCountsByType.good_sleep || 0) >= 10,
    rewards: { 'ХП': 3 },
  },
  // ── ХОДЬБА: секретные ──
  {
    id: 'secret_sunday_philosopher',
    title: 'Воскресный философ',
    hint: 'Шаги и чтение в один особый день',
    check: (ctx) => ctx.sundayStepsAndReading,
  },
  {
    id: 'secret_rain_no_stop',
    title: 'Дождь не помеха',
    hint: '30 дней подряд без пропуска 5к+ шагов',
    check: (ctx) => ctx.stepsStreak5k30,
  },
  {
    id: 'secret_quiet_ride',
    title: 'Тише едешь',
    hint: '30к шагов + беговая тренировка в один день',
    check: (ctx) => ctx.steps30kWithRun,
  },
  {
    id: 'secret_record_legend',
    title: 'Легенда, которую помнят',
    hint: 'Один и тот же рекорд побит 5 раз',
    check: (ctx) => Object.values(ctx.personalRecords || {}).some(r => (r.timesBroken || 0) >= 5),
  },
];

// Combo achievements: repeatable, triggered every day the required activity set is logged together.
// Each trigger grants an immediate flat stat reward and increments a counter (shown in the UI).
// 'strength' in requires means either strength_park OR strength_gym counts.
export const COMBO_ACHIEVEMENTS = [
  {
    id: 'combo_spartan',
    title: 'Тройной удар: Спартанец',
    requires: ['strength', 'running', 'sleep'],
    description: 'Силовая тренировка + бег + здоровый сон в один день',
    rewards: { 'Сила': 5, 'Выносливость': 5, 'ХП': 5 },
  },
  {
    id: 'combo_sage',
    title: 'Тройной удар: Мудрец путей',
    requires: ['reading', 'nutrition', 'sleep'],
    description: 'Чтение + правильное питание + здоровый сон в один день',
    rewards: { 'Мышление': 5, 'Дисциплина': 5, 'Дух': 5 },
  },
  {
    id: 'combo_hermit',
    title: 'Тройной удар: Аскетичный отшельник',
    requires: ['strength_park', 'nutrition', 'reading'],
    description: 'Турники + правильное питание + чтение в один день',
    rewards: { 'Упорство': 5, 'Фокус': 5, 'Интеллект': 5 },
  },
  {
    id: 'combo_berserker',
    title: 'Тройной удар: Берсерк',
    requires: ['wrestling', 'strength', 'running'],
    description: 'Единоборства + силовая + бег в один день',
    rewards: { 'Силовая выносливость': 5, 'Упорство': 5, 'Воля': 5 },
  },
  {
    id: 'combo_walk_after_battle',
    title: 'Прогулка после боя',
    requires: ['walking_12k', 'strength', 'nutrition'],
    description: '12к+ шагов + силовая + питание в один день',
    rewards: { 'Упорство': 4, 'Выносливость': 4 },
  },
  {
    id: 'combo_path_of_sage',
    title: 'Путь мудреца',
    requires: ['walking_10k', 'reading', 'sleep'],
    description: '10к+ шагов + чтение + здоровый сон в один день',
    rewards: { 'Мышление': 4, 'Дух': 4 },
  },
  {
    id: 'combo_ash_in_wind',
    title: 'Пепел на ветру',
    requires: ['walking_10k', 'calories_800'],
    consecutiveDays: 5,
    legendary: true,
    description: '10к+ шагов и 800+ ккал сожжено — 5 дней подряд',
    rewards: { 'Выносливость': 10, 'Дисциплина': 10, 'Воля': 10 },
  },
  {
    id: 'combo_full_circle',
    title: 'Полный круг',
    requires: ['walking_6k', 'running', 'strength', 'wrestling', 'nutrition', 'sleep', 'reading'],
    consecutiveDays: 5,
    description: '6к+ шагов и все активности в один день — 5 дней подряд',
    rewards: { 'Дисциплина': 6, 'Воля': 6, 'Дух': 6 },
  },
];

// "Баланс" achievements: reward keeping two different activities in proportion over a rolling
// 14-day window, or maintaining a dual streak. Repeatable — each qualifying window/block counts.
export const BALANCE_ACHIEVEMENTS = [
  {
    id: 'balance_weighted',
    title: 'Взвешенный',
    kind: 'equal_count_window',
    activitiesA: ['strength_park', 'strength_gym'],
    activitiesB: ['running'],
    windowDays: 14,
    minEach: 5,
    description: 'Любые 14 дней, где количество силовых и беговых тренировок совпадает (от 5 и больше каждой)',
    rewards: { 'Выносливость': 5, 'Сила': 5 },
  },
  {
    id: 'balance_harmonious',
    title: 'Уравновешенный',
    kind: 'equal_count_window',
    activitiesA: ['strength_park', 'strength_gym'],
    activitiesB: ['reading'],
    windowDays: 14,
    minEach: 6,
    description: 'Любые 14 дней, где количество силовых тренировок и дней чтения совпадает (от 6 и больше каждой)',
    rewards: { 'Интеллект': 5, 'Сила': 5, 'Дух': 5 },
  },
  {
    id: 'balance_hedonist',
    title: 'Здоровенный гедонист',
    kind: 'dual_streak_block',
    activitiesA: ['nutrition'],
    activitiesB: ['sleep'],
    blockDays: 14,
    description: '14 дней подряд, где правильное питание и здоровый сон отмечены одновременно',
    rewards: { 'ХП': 10, 'Дисциплина': 10 },
  },
];

