// ---------- STYLES ----------

export const styles = {
  app: {
    minHeight: '100vh',
    background: '#15151a',
    color: '#e8e8ec',
    fontFamily: '"Montserrat", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    maxWidth: 520,
    margin: '0 auto',
    paddingBottom: 40,
    position: 'relative',
  },
  header: {
    padding: '20px 18px 14px',
    borderBottom: '1px solid #25252c',
  },
  headerRow: { display: 'flex', alignItems: 'center', gap: 12 },
  avatarCircle: {
    width: 76, height: 96, borderRadius: '50%',
    background: '#241c10', borderWidth: 1, borderStyle: 'solid', borderColor: '#4a3a1f',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    flexShrink: 0, transition: 'background 0.3s ease, border-color 0.3s ease',
  },
  charName: { fontSize: 19, fontWeight: 700, color: '#f0f0f4' },
  charNameBtn: {
    display: 'flex', alignItems: 'center', gap: 6, background: 'none', border: 'none',
    cursor: 'pointer', padding: 0, maxWidth: '100%',
  },
  charNameInput: {
    fontSize: 19, fontWeight: 700, color: '#f0f0f4', background: '#15151a',
    border: '1px solid #e0a868', borderRadius: 6, padding: '2px 7px',
    outline: 'none', width: '100%', maxWidth: 220,
  },
  charLevel: { fontSize: 12, color: '#8a8a92', marginTop: 1 },
  classBadge: {
    display: 'inline-flex', alignItems: 'center', marginTop: 5,
    border: '1px solid', borderRadius: 7, padding: '2px 8px',
    fontSize: 10.5, fontWeight: 700,
  },
  headerClassStrip: { display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: 4, marginTop: 4 },
  headerClassChip: {
    display: 'inline-flex', alignItems: 'center', gap: 4,
    fontSize: 9.5, fontWeight: 700, border: '1px solid',
    borderRadius: 6, padding: '2px 6px', letterSpacing: 0.2,
  },
  headerClassSep: { fontSize: 9, color: '#4a4a52', flexShrink: 0 },
  achBadge: {
    display: 'flex', alignItems: 'center', fontSize: 12, fontWeight: 600,
    color: '#f0d272', background: '#241c10', border: '1px solid #4a3a1f',
    borderRadius: 20, padding: '6px 11px',
  },
  levelBarWrap: { marginTop: 12 },
  levelBarTrack: {
    height: 10, background: '#24242b', borderRadius: 6, overflow: 'hidden',
    border: '1px solid #2c2c34',
  },
  levelBarFill: {
    height: '100%', borderRadius: 6,
    background: 'linear-gradient(90deg, #c9852f 0%, #e0a868 50%, #f0d272 100%)',
    transition: 'width 0.6s cubic-bezier(0.22, 1, 0.36, 1)',
    boxShadow: '0 0 8px rgba(240,210,114,0.4)',
  },
  levelBarLabelRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: 5, gap: 8 },
  levelBarLabel: { fontSize: 10.5, color: '#7a7a82' },
  currencyBadge: {
    display: 'flex', alignItems: 'center', fontSize: 11, fontWeight: 700, color: '#5b9bf0',
    background: '#162236', border: '1px solid #2a3f5c', borderRadius: 8, padding: '2px 7px',
    flexShrink: 0,
  },
  healthBarsWrap: { display: 'flex', flexDirection: 'column', gap: 8, marginTop: 14 },
  healthBarItem: {},
  healthBarLabelRow: { display: 'flex', alignItems: 'center', gap: 5, marginBottom: 4 },
  healthBarLabel: { fontSize: 11, color: '#9a9aa2', flex: 1 },
  healthBarValue: { fontSize: 11, color: '#7a7a82', fontWeight: 600 },
  debuffBadge: {
    display: 'inline-flex', alignItems: 'center', gap: 4, marginTop: 5,
    background: '#3a1424', border: '1px solid #6e2540', borderRadius: 7,
    padding: '3px 8px',
  },
  debuffBadgeText: { fontSize: 10.5, fontWeight: 700, color: '#ff8fa8' },
  xpBlockedBanner: {
    marginTop: 12, padding: '8px 11px', borderRadius: 8, fontSize: 11, lineHeight: 1.4,
    background: '#3a1a1a', border: '1px solid #6a2a2a', color: '#f0a8a8',
  },
  poisonVialsRow: {
    display: 'flex', alignItems: 'center', gap: 5,
    marginTop: 7,
  },
  poisonVialsLabel: { fontSize: 11, fontWeight: 600, color: '#c9a8f5', marginLeft: 3 },
  tabBar: {
    display: 'flex', flexWrap: 'wrap', padding: '6px 14px 4px', borderBottom: '1px solid #25252c', gap: 2,
  },
  tabBtn: {
    background: 'none', border: 'none', padding: '7px 8px', fontSize: 12,
    fontWeight: 600, cursor: 'pointer', whiteSpace: 'nowrap',
  },
  content: { padding: '18px 18px 0' },
  sectionLabel: {
    fontSize: 11.5, fontWeight: 700, color: '#6a6a72', textTransform: 'uppercase',
    letterSpacing: 0.6, marginBottom: 12,
  },
  activityGrid: {
    display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10,
    gridAutoFlow: 'row dense',
  },
  passiveGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 },
  recoveryWrap: {
    marginTop: 20, padding: '14px 14px 16px', borderRadius: 16,
    background: 'linear-gradient(165deg, #123832 0%, #0f2622 100%)',
    border: '1px solid #1f6e5c', boxShadow: '0 0 0 1px rgba(76,224,192,0.08), 0 8px 24px rgba(15,38,34,0.5)',
  },
  recoverySectionHeader: { display: 'flex', alignItems: 'center', gap: 7, marginBottom: 12, flexWrap: 'wrap' },
  recoverySectionTitle: { fontSize: 13.5, fontWeight: 700, color: '#4ce0c0' },
  recoverySectionSub: { fontSize: 10.5, color: '#5fa896' },
  recoveryGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 },
  recoveryCard: {
    display: 'flex', alignItems: 'center', gap: 8, background: '#0f2622aa',
    border: '1px solid #1f6e5c88', borderRadius: 10, padding: '10px 11px',
    cursor: 'pointer', textAlign: 'left',
  },
  recoveryCardLabel: { fontSize: 12, fontWeight: 600, color: '#d6f5ec', lineHeight: 1.25 },
  passiveCard: {
    display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 6,
    border: '1px solid', borderRadius: 12, padding: '12px 6px', cursor: 'pointer',
    transition: 'background 0.15s ease, border-color 0.15s ease',
  },
  passiveLabel: { fontSize: 11.5, fontWeight: 600 },
  activityCard: {
    position: 'relative', background: '#212128', border: '1px solid #323240',
    borderRadius: 14, textAlign: 'left', overflow: 'hidden',
    display: 'flex', flexDirection: 'column', color: 'inherit',
  },
  cardPlusBtn: {
    position: 'absolute', top: 10, right: 10, background: 'rgba(10,10,13,0.55)',
    border: '1px solid rgba(255,255,255,0.18)', borderRadius: '50%', width: 26, height: 26,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    cursor: 'pointer', padding: 0, zIndex: 2,
  },
  cardExpand: {
    display: 'flex', flexDirection: 'column', gap: 10, margin: '4px 12px 14px',
    paddingTop: 10, borderTop: '1px solid #25252c', animation: 'fadeUp 0.2s ease',
  },
  cardExpandEmpty: { fontSize: 11, color: '#5a5a62' },
  bookTrackerWrap: { marginTop: 4, paddingTop: 10, borderTop: '1px solid #25252c' },
  bookTrackerLabel: { fontSize: 11, color: '#9a9aa2', marginBottom: 8, fontWeight: 600 },
  bookInputRow: { display: 'flex', gap: 6, marginBottom: 8 },
  bookInput: {
    flex: 1, background: '#15151a', border: '1px solid #2c2c34', borderRadius: 8,
    padding: '7px 10px', color: '#f0f0f4', fontSize: 12.5, outline: 'none',
  },
  bookAddBtn: {
    background: '#e0a868', border: 'none', borderRadius: 8, width: 30,
    display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', flexShrink: 0,
  },
  bookList: { display: 'flex', flexDirection: 'column', gap: 6 },
  bookRow: { display: 'flex', alignItems: 'center', gap: 8 },
  bookCheck: {
    width: 18, height: 18, borderRadius: 5, border: '1px solid',
    display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', flexShrink: 0,
  },
  bookTitle: { fontSize: 12.5, color: '#dcdce2', flex: 1 },
  bookRemoveBtn: { background: 'none', border: 'none', cursor: 'pointer', padding: 2, flexShrink: 0 },
  miniProgressBlock: {},
  miniProgressLabelRow: { display: 'flex', justifyContent: 'space-between', marginBottom: 5, gap: 6 },
  miniProgressLabel: { fontSize: 11, color: '#9a9aa2', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  miniProgressValue: { fontSize: 11, color: '#7a7a82', fontWeight: 600, flexShrink: 0 },
  activityIconWrap: {
    width: 34, height: 34, borderRadius: 9, display: 'flex',
    alignItems: 'center', justifyContent: 'center', flexShrink: 0,
  },
  activityIconBg: {
    position: 'absolute', top: -6, right: -8, opacity: 0.32,
    pointerEvents: 'none',
  },
  activityBgImage: {
    position: 'absolute', top: 0, left: 0, width: '100%', height: '100%',
    objectFit: 'cover', opacity: 0.34, pointerEvents: 'none',
  },
  activityCardTextOverlay: {
    position: 'absolute', inset: 0, padding: '14px 12px',
    display: 'flex', flexDirection: 'column', justifyContent: 'flex-end', gap: 8,
  },
  activityCardLabel: {
    fontSize: 15.5, fontWeight: 700, color: '#f0f0f4', lineHeight: 1.25,
    position: 'relative', maxWidth: '78%',
  },
  streakPill: {
    display: 'flex', alignItems: 'center', fontSize: 11, fontWeight: 600,
    color: '#e0a868', background: '#241c10', borderRadius: 10, padding: '2px 7px',
    alignSelf: 'flex-start', gap: 3,
  },
  statGrid: { display: 'flex', flexDirection: 'column', gap: 12 },
  radarWrap: {
    background: '#1c1c22', border: '1px solid #28282f', borderRadius: 14,
    padding: '16px 8px 14px', display: 'flex', flexDirection: 'column', alignItems: 'center',
  },
  radarLegend: { display: 'flex', flexWrap: 'wrap', gap: '6px 14px', justifyContent: 'center', marginTop: 10 },
  radarLegendItem: { display: 'flex', alignItems: 'center', gap: 5, fontSize: 11, color: '#9a9aa2' },
  radarLegendDot: { width: 8, height: 8, borderRadius: '50%', flexShrink: 0 },
  equippedGearWrap: {
    background: '#1c1c22', border: '1px solid #28282f', borderRadius: 14,
    padding: '16px', display: 'flex', flexDirection: 'column', gap: 14,
  },
  equippedCardsRow: { display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 8 },
  equippedGearCard: {
    border: '1px solid', borderRadius: 12, padding: '14px 8px',
    display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 6, textAlign: 'center',
  },
  equippedGearIconWrap: {
    width: 52, height: 52, borderRadius: 12, display: 'flex',
    alignItems: 'center', justifyContent: 'center',
  },
  equippedGearSlotLabel: { fontSize: 9, color: '#7a7a82', textTransform: 'uppercase', letterSpacing: 0.4 },
  equippedGearItemName: { fontSize: 11, fontWeight: 700, lineHeight: 1.25, minHeight: 28 },
  equippedBonusSummary: { borderTop: '1px solid #28282f', paddingTop: 12 },
  equippedBonusSummaryTitle: {
    fontSize: 10.5, fontWeight: 700, color: '#6a6a72', textTransform: 'uppercase',
    letterSpacing: 0.4, marginBottom: 8,
  },
  equippedBonusList: { display: 'flex', flexDirection: 'column', gap: 6 },
  equippedBonusRow: {
    display: 'flex', justifyContent: 'space-between', alignItems: 'center',
    padding: '7px 11px', background: '#15151a', borderRadius: 8,
  },
  equippedBonusActivity: { fontSize: 12, color: '#dcdce2', fontWeight: 600 },
  equippedBonusValue: { fontSize: 12.5, color: '#5b9bf0', fontWeight: 700 },
  equippedEmptyHint: { fontSize: 11.5, color: '#7a7a82', textAlign: 'center', lineHeight: 1.5 },
  classCardWrap: {
    display: 'flex', alignItems: 'center', gap: 14, border: '2px solid #28282f',
    background: '#1c1c22', borderRadius: 14, padding: '16px 16px',
  },
  classCardEmpty: { fontSize: 12.5, color: '#7a7a82', textAlign: 'center', width: '100%' },
  classCardIconWrap: {
    width: 60, height: 60, borderRadius: 14, display: 'flex',
    alignItems: 'center', justifyContent: 'center', flexShrink: 0,
  },
  classCardName: { fontSize: 19, fontWeight: 800, marginBottom: 3, letterSpacing: 0.2 },
  classCardComboTag: {
    display: 'inline-block', fontSize: 9.5, fontWeight: 800, color: '#15151a',
    background: '#f5c84a', borderRadius: 5, padding: '2px 6px', marginRight: 7,
    verticalAlign: 'middle', letterSpacing: 0.4,
  },
  classCardDesc: { fontSize: 11.5, color: '#9a9aa2', lineHeight: 1.4 },
  statRow: {},
  statLabelRow: { display: 'flex', justifyContent: 'space-between', marginBottom: 5 },
  statLabel: { fontSize: 12.5, color: '#aeaeb6' },
  statValue: { fontSize: 12.5, color: '#7a7a82', fontWeight: 600 },
  statBarTrack: { height: 6, background: '#24242b', borderRadius: 4, overflow: 'hidden' },
  statBarFill: { height: '100%', background: '#7a6ae0', borderRadius: 4, transition: 'width 0.4s ease' },
  progressRow: {
    background: '#1c1c22', border: '1px solid #28282f', borderRadius: 12,
    padding: '12px 14px', display: 'flex', gap: 10,
  },
  progressTitle: { fontSize: 13, fontWeight: 600, color: '#dcdce2', marginBottom: 3 },
  progressSub: { fontSize: 11.5, color: '#8a8a92', marginBottom: 7 },
  achSection: { marginBottom: 30 },
  mythicHeader: { display: 'flex', alignItems: 'center', gap: 8, marginBottom: 16 },
  mythicHeaderTitle: { fontSize: 14, fontWeight: 700, color: '#f5c84a' },
  mythicHeaderCount: {
    fontSize: 11, fontWeight: 700, color: '#1c1505', background: '#f5c84a',
    borderRadius: 9, padding: '1px 8px', marginLeft: 2,
  },
  mythicCard: {
    border: '1.5px solid', borderRadius: 14, padding: '14px 14px',
    textAlign: 'left', width: '100%', cursor: 'pointer',
  },
  mythicCardTop: { display: 'flex', alignItems: 'center', gap: 10 },
  mythicTitle: { fontSize: 13.5, fontWeight: 700, lineHeight: 1.3 },
  mythicCharacter: { fontSize: 11, color: '#8a8a92', marginTop: 2 },
  mythicExpand: {
    marginTop: 12, paddingTop: 12, borderTop: '1px solid #2c2c34',
    animation: 'fadeUp 0.2s ease',
  },
  mythicConditionLabel: {
    fontSize: 10, fontWeight: 700, color: '#6a6a72', textTransform: 'uppercase',
    letterSpacing: 0.4, marginBottom: 4,
  },
  mythicConditionText: { fontSize: 12, color: '#9a9aa2', lineHeight: 1.5, marginBottom: 10 },
  mythicQuote: {
    fontSize: 12.5, color: '#f0d272', fontStyle: 'italic', lineHeight: 1.5,
    paddingTop: 8, borderTop: '1px solid #3a2f10',
  },
  classTreeHint: {
    fontSize: 11.5, color: '#7a7a82', lineHeight: 1.5, marginBottom: 20, textAlign: 'center',
  },
  classTreeSection: { marginBottom: 24 },
  classTreeNode: {
    display: 'flex', alignItems: 'center', gap: 12, border: '1.5px solid',
    borderRadius: 14, padding: '12px 14px',
  },
  classTreeNodeIconWrap: {
    width: 42, height: 42, borderRadius: 11, display: 'flex',
    alignItems: 'center', justifyContent: 'center', flexShrink: 0,
  },
  classTreeNodeName: { fontSize: 15, fontWeight: 800 },
  classTreeNodeGroup: { fontSize: 11, color: '#8a8a92', marginTop: 1 },
  classTreeActiveBadge: {
    fontSize: 9.5, fontWeight: 800, color: '#15151a', borderRadius: 6,
    padding: '3px 8px', flexShrink: 0,
  },
  classTreeBranchLine: {
    width: 2, height: 14, background: '#28282f', marginLeft: 27,
  },
  classTreeItemsRow: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8, marginLeft: 8 },
  classTreeItemCard: {
    border: '1px solid', borderRadius: 12, padding: '12px 8px',
    display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4, textAlign: 'center',
  },
  classTreeItemName: { fontSize: 11, fontWeight: 700, color: '#dcdce2', lineHeight: 1.25, minHeight: 28 },
  shopBalanceWrap: {
    display: 'flex', alignItems: 'center', gap: 6, background: '#162236',
    border: '1px solid #2a3f5c', borderRadius: 12, padding: '10px 14px', marginBottom: 18,
  },
  shopBalanceValue: { fontSize: 17, fontWeight: 700, color: '#5b9bf0' },
  shopBalanceLabel: { fontSize: 12, color: '#7a8fa8' },
  shopRarityTabs: {
    display: 'flex', gap: 6, marginBottom: 14, overflowX: 'auto', overflowY: 'hidden',
    scrollbarWidth: 'none', paddingBottom: 2,
  },
  shopRarityTabBtn: {
    display: 'flex', alignItems: 'center', gap: 5, border: '1px solid', borderRadius: 9,
    padding: '7px 11px', fontSize: 11.5, fontWeight: 700, cursor: 'pointer',
    whiteSpace: 'nowrap', flexShrink: 0,
  },
  shopRarityTabCount: { fontSize: 9.5, opacity: 0.7, marginLeft: 1 },
  shopRaritySectionHeader: { display: 'flex', alignItems: 'center', gap: 7, marginBottom: 9 },
  shopRaritySectionDot: { width: 8, height: 8, borderRadius: '50%', flexShrink: 0 },
  shopRaritySectionTitle: { fontSize: 12.5, fontWeight: 700, textTransform: 'uppercase', letterSpacing: 0.4 },
  shopRaritySectionCount: { fontSize: 10.5, color: '#6a6a72', marginLeft: 'auto' },
  shopGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(100px, 1fr))', gap: 7 },
  shopCard: {
    border: '1px solid', borderRadius: 11, padding: '9px 6px',
    display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 3, textAlign: 'center',
  },
  shopCardIconWrap: {
    width: 30, height: 30, borderRadius: 8, display: 'flex',
    alignItems: 'center', justifyContent: 'center', marginBottom: 1,
  },
  shopItemName: { fontSize: 10, fontWeight: 600, color: '#dcdce2', lineHeight: 1.2, minHeight: 24 },
  shopItemBonus: { fontSize: 8.5, color: '#7a7a82', lineHeight: 1.2 },
  shopItemLockedHint: { fontSize: 8.5, color: '#6a6a72', fontStyle: 'italic', lineHeight: 1.2 },
  shopActionBtnSmall: {
    marginTop: 4, border: '1px solid', borderRadius: 7, padding: '4px 6px',
    fontSize: 10, fontWeight: 700, display: 'flex', alignItems: 'center', justifyContent: 'center',
    width: '100%',
  },
  hallOfFameWrap: { marginBottom: 26 },
  hallOfFameHeader: { display: 'flex', alignItems: 'center', gap: 7, marginBottom: 10 },
  hallOfFameTitle: { fontSize: 13, fontWeight: 700, color: '#d4af37' },
  hallOfFameCount: {
    fontSize: 10.5, fontWeight: 700, color: '#0f0c05', background: '#d4af37',
    borderRadius: 9, padding: '1px 7px', marginLeft: 2,
  },
  hallOfFameScroll: {
    display: 'flex', gap: 8, overflowX: 'auto', overflowY: 'hidden',
    paddingBottom: 4, scrollbarWidth: 'none',
  },
  hallOfFameMedal: {
    display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4,
    border: '1px solid', borderRadius: 10, padding: '8px 10px',
    flexShrink: 0, minWidth: 64, maxWidth: 84,
  },
  hallOfFameMedalName: {
    fontSize: 9.5, fontWeight: 700, textAlign: 'center', lineHeight: 1.2,
    overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', maxWidth: '100%',
  },
  achSectionHeader: {
    display: 'flex', alignItems: 'center', gap: 8, marginBottom: 14,
    paddingBottom: 8, borderBottom: '1px solid #25252c',
  },
  achSectionTitle: { fontSize: 14, fontWeight: 700 },
  secretGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 },
  secretCard: {
    border: '1px solid', borderRadius: 12, padding: '12px 10px',
    display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 6, textAlign: 'center',
  },
  secretTitle: { fontSize: 11.5, fontWeight: 700, lineHeight: 1.25 },
  secretHint: { fontSize: 10, color: '#6a6a72', lineHeight: 1.3 },
  comboList: { display: 'flex', flexDirection: 'column', gap: 8 },
  comboCard: { border: '1px solid', borderRadius: 12, padding: '10px 12px' },
  comboCardTop: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 8, marginBottom: 4 },
  comboTitle: { fontSize: 12.5, fontWeight: 700 },
  comboCount: { display: 'flex', alignItems: 'center', gap: 3, fontSize: 11.5, fontWeight: 700, color: '#e0a868', flexShrink: 0 },
  comboReward: { fontSize: 11, color: '#7a7a82' },
  comboCondition: {
    fontSize: 11, color: '#9a9aa2', marginTop: 8, paddingTop: 8,
    borderTop: '1px solid #2c2c34', lineHeight: 1.4, animation: 'fadeUp 0.2s ease',
  },
  pentaCard: { border: '1.5px solid', borderRadius: 12, padding: '12px 14px' },
  achGroup: { marginBottom: 22 },
  achGroupHeader: {
    fontSize: 13.5, fontWeight: 600, color: '#dcdce2', marginBottom: 10,
    display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', flexWrap: 'wrap', gap: 6,
  },
  achFlavor: { fontSize: 11, color: '#6a6a72', fontWeight: 400 },
  tierRow: { display: 'flex', gap: 8, flexWrap: 'wrap' },
  achGroupProgress: { marginTop: 10 },
  tierCard: {
    flex: '1 1 90px', minWidth: 90, border: '1px solid', borderRadius: 12,
    padding: '12px 10px', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 5,
  },
  tierName: { fontSize: 11.5, fontWeight: 700, textAlign: 'center', lineHeight: 1.25 },
  tierNeed: { fontSize: 10.5, color: '#6a6a72' },
  historyRow: {
    display: 'flex', alignItems: 'center', gap: 10, padding: '10px 0',
    borderBottom: '1px solid #202026',
  },
  historyLabel: { fontSize: 13.5, fontWeight: 600, color: '#dcdce2' },
  historyDate: { fontSize: 11.5, color: '#7a7a82', marginTop: 2, display: 'flex', alignItems: 'center' },
  emptyState: { fontSize: 13, color: '#7a7a82', textAlign: 'center', padding: '40px 20px' },
  archiveEmptyState: {
    display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 10,
    textAlign: 'center', padding: '50px 24px', color: '#9a9aa2',
  },
  archiveEmptyTitle: { fontSize: 15, fontWeight: 700, color: '#dcdce2' },
  archiveEmptyText: { fontSize: 12.5, lineHeight: 1.6, maxWidth: 280 },
  modalOverlay: {
    position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.55)',
    display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 50, padding: 20,
  },
  modalCard: {
    background: '#1c1c22', border: '1px solid #2c2c34', borderRadius: 16,
    padding: 20, width: '100%', maxWidth: 360, animation: 'popIn 0.2s ease',
  },
  modalHeader: { display: 'flex', alignItems: 'center' },
  modalTitle: { fontSize: 15, fontWeight: 600, color: '#f0f0f4' },
  modalSub: { fontSize: 12, color: '#8a8a92', marginTop: 1 },
  modalClose: { background: 'none', border: 'none', cursor: 'pointer', padding: 4 },
  fieldLabel: { fontSize: 12, color: '#aeaeb6', display: 'block', marginBottom: 6 },
  input: {
    width: '100%', background: '#15151a', border: '1px solid #2c2c34', borderRadius: 10,
    padding: '10px 12px', color: '#f0f0f4', fontSize: 15, outline: 'none',
  },
  strictSleepRow: {
    display: 'flex', alignItems: 'center', gap: 8, marginTop: 12,
    background: 'none', border: 'none', cursor: 'pointer', padding: 0, textAlign: 'left',
  },
  strictSleepCheck: {
    width: 18, height: 18, borderRadius: 5, border: '1px solid', flexShrink: 0,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
  },
  strictSleepLabel: { fontSize: 12.5, color: '#aeaeb6' },
  intensityRow: { display: 'flex', gap: 6 },
  intensityBtn: {
    flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center',
    border: '1px solid', borderRadius: 10, padding: '10px 6px', fontSize: 12,
    cursor: 'pointer', transition: 'all 0.15s ease',
  },
  statsPreview: {
    display: 'flex', alignItems: 'center', fontSize: 11.5, color: '#6a6a72',
    marginTop: 16, padding: '8px 10px', background: '#15151a', borderRadius: 8,
  },
  submitBtn: {
    width: '100%', marginTop: 16, background: '#e0a868', color: '#1c1505',
    border: 'none', borderRadius: 10, padding: '12px 0', fontSize: 14.5,
    fontWeight: 700, cursor: 'pointer',
  },
  toast: {
    position: 'fixed', top: 24, left: '50%', transform: 'translateX(-50%)',
    background: '#1c1c22', border: '1px solid #4a3a1f', borderRadius: 30,
    padding: '10px 18px', fontSize: 13, color: '#f0d272', display: 'flex',
    alignItems: 'center', boxShadow: '0 8px 24px rgba(0,0,0,0.4)',
    animation: 'fadeUp 0.25s ease', zIndex: 60,
  },
};

